const FETCH_USER = "FETCH_USER";
const SET_IS_SIGNING_IN = "SET_IS_SIGNING_IN";
const SET_IS_SIGNING_UP = "SET_IS_SIGNING_UP";
const LOGOUT = "LOGOUT";

export {
    SET_IS_SIGNING_IN,
    SET_IS_SIGNING_UP,
    FETCH_USER,
    LOGOUT
};