const FETCH_USER = "FETCH_USER";
const SET_IS_SIGNING_IN = "SET_IS_SIGNING_IN";
const SET_IS_SIGNING_UP = "SET_IS_SIGNING_UP";
const SET_IS_UPDATING_EMAIL = "SET_IS_UPDATING_EMAIL";
const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";
const LOGOUT = "LOGOUT";

export {
    SET_IS_UPDATING_EMAIL,
    UPDATE_USER_EMAIL,
    SET_IS_SIGNING_IN,
    SET_IS_SIGNING_UP,
    FETCH_USER,
    LOGOUT
};