const FETCH_USER = "FETCH_USER";
const SET_IS_SIGNING_IN = "SET_IS_SIGNING_IN";
const SET_IS_SIGNING_UP = "SET_IS_SIGNING_UP";
const SET_IS_UPDATING_EMAIL = "SET_IS_UPDATING_EMAIL";
const SET_IS_UPDATING_PASSWORD = "SET_IS_UPDATING_PASSWORD";
const SET_IS_UPDATING_PHONE_NO = "SET_IS_UPDATING_PHONE_NO";
const SET_IS_UPDATING_IMAGE = "SET_IS_UPDATING_IMAGE";
const SET_IS_UPDATING_ADDRESS = "SET_IS_UPDATING_ADDRESS";
const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";
const UPDATE_USER_IMAGE = "UPDATE_USER_IMAGE";
const UPDATE_USER_PHONE_NO = "UPDATE_USER_PHONE_NO";
const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
const LOGOUT = "LOGOUT";

const SET_IS_FETCHING_CASE_DETAILS = "SET_IS_FETCHING_CASE_DETAILS";
const SET_IS_FORM_POSTING = "SET_IS_FORM_POSTING";
const SET_IS_FETCHING_CASES = "SET_IS_FETCHING_CASES";
const SET_USER_CASE_DETAILS = "SET_USER_CASE_DETAILS";
const SET_USER_CASES = "SET_USER_CASES";

export {
    SET_IS_FETCHING_CASE_DETAILS,
    SET_IS_UPDATING_PHONE_NO,
    SET_IS_UPDATING_PASSWORD,
    SET_IS_UPDATING_ADDRESS,
    SET_USER_CASE_DETAILS,
    SET_IS_UPDATING_IMAGE,
    SET_IS_UPDATING_EMAIL,
    SET_IS_FETCHING_CASES,
    UPDATE_USER_PHONE_NO,
    UPDATE_USER_ADDRESS,
    SET_IS_FORM_POSTING,
    UPDATE_USER_IMAGE,
    UPDATE_USER_EMAIL,
    SET_IS_SIGNING_IN,
    SET_IS_SIGNING_UP,
    SET_USER_CASES,
    FETCH_USER,
    LOGOUT
};